/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/post.json": {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                page?: components["parameters"]["Page"];
                tags?: components["parameters"]["Tags"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Posts list */
        get: operations["list_posts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/post.json?api_version=2": {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                page?: components["parameters"]["Page"];
                tags?: components["parameters"]["Tags"];
                include_tags?: 0 | 1;
                include_votes?: 0 | 1;
                include_pools?: 0 | 1;
                filter?: 0 | 1;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Posts list v2 */
        get: operations["list_posts_v2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tag.json": {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                limit?: number;
                order?: "date" | "count" | "name";
                id?: number;
                after_id?: number;
                name?: string;
                name_pattern?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Tags list */
        get: operations["list_tags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tag/related.json": {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                page?: components["parameters"]["Page"];
                order?: "date" | "count" | "name";
                id?: number;
                after_id?: number;
                name?: string;
                name_pattern?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Tags list */
        get: operations["list_related_tags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artist.json": {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                name?: string;
                order?: "date" | "name";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Artist list */
        get: operations["list_artist"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user.json": {
        parameters: {
            query?: {
                id?: number;
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Users list */
        get: operations["list_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pool.json": {
        parameters: {
            query?: {
                query?: string;
                page?: components["parameters"]["Page"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Pool list */
        get: operations["list_pools"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pool/show.json": {
        parameters: {
            query: {
                id: number;
                page?: components["parameters"]["Page"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Pool posts list */
        get: operations["list_pool_posts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        artists: {
            /** @description The ID */
            id: number;
            name: string;
            alias_id: number | null;
            group_id: number | null;
            urls: string[];
        }[];
        /** @description The number of results to show per page */
        page: number;
        poolPosts: {
            /** @description The ID */
            id: number;
            name: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** @description The ID */
            user_id: number;
            is_public: boolean;
            post_count: number;
            description: string;
            posts: components["schemas"]["posts"];
        };
        pools: {
            /** @description The ID */
            id: number;
            /** @description The ID */
            pool_id: number;
            /** @description The ID */
            post_id: number;
            active: boolean;
            sequence: string;
            /** @description The ID */
            next_post_id: number;
            prev_post_id: number | null;
        }[];
        posts: {
            /** @description The post ID */
            id: number;
            tags: string;
            /** @description The timestamp when the post was created */
            created_at: number;
            /** @description The timestamp when the post was last updated */
            updated_at: number;
            /** @description The ID */
            creator_id: number;
            approver_id: number | null;
            author: string;
            change: number;
            source: string;
            score: number;
            md5: string;
            is_shown_in_index: boolean;
            actual_preview_width: number;
            actual_preview_height: number;
            width: number;
            height: number;
            /** Format: uri */
            file_url: string;
            /** @enum {string} */
            file_ext: "jpg" | "png" | "gif" | "avif" | "mp4" | "webp" | "webm" | "swf" | "zip";
            file_size: number;
            /** Format: uri */
            preview_url: string;
            preview_width: number;
            preview_height: number;
            /** Format: uri */
            sample_url: string;
            sample_width: number;
            sample_height: number;
            sample_file_size: number;
            /** Format: uri */
            jpeg_url: string;
            jpeg_width: number;
            jpeg_height: number;
            jpeg_file_size: number;
            /** @enum {string} */
            status: "active";
            /**
             * @description The rating of the post
             * @enum {string}
             */
            rating: "g" | "s" | "q" | "e";
            is_rating_locked: boolean;
            has_children: boolean;
            parent_id: number | null;
            is_pending: boolean;
            is_held: boolean;
            frames_pending_string: string;
            frames_pending: unknown[];
            frames_string: string;
            frames: unknown[];
            is_note_locked: boolean;
            last_noted_at: number;
            last_commented_at: number;
        }[];
        postV2: {
            posts: components["schemas"]["posts"];
            pool_posts?: {
                /** @description The ID */
                id: number;
                /** @description The ID */
                pool_id: number;
                /** @description The ID */
                post_id: number;
                active: boolean;
                sequence: string;
                /** @description The ID */
                next_post_id: number;
                prev_post_id: number | null;
            }[];
            pools?: {
                /** @description The ID */
                id: number;
                name: string;
                /** Format: date-time */
                created_at: string;
                /** Format: date-time */
                updated_at: string;
                /** @description The ID */
                user_id: number;
                is_public: boolean;
                post_count: number;
                description: string;
            }[];
            tags?: {
                [key: string]: "general" | "artist" | "copyright" | "character" | "circle";
            };
        };
        tagRelated: {
            [key: string]: [
                string,
                string
            ];
        };
        tags: {
            /** @description The ID */
            id: number;
            name: string;
            count: number;
            /** @enum {number} */
            type: 0 | 1 | 3 | 4;
            ambiguous: boolean;
        }[];
        users: {
            /** @description The ID */
            id: number;
            name: string;
            alias_id: number | null;
            group_id: number | null;
            urls: string[];
        }[];
    };
    responses: never;
    parameters: {
        Limit: number;
        Page: components["schemas"]["page"];
        Tags: string | string[];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_posts: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                page?: components["parameters"]["Page"];
                tags?: components["parameters"]["Tags"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["posts"];
                };
            };
        };
    };
    list_posts_v2: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                page?: components["parameters"]["Page"];
                tags?: components["parameters"]["Tags"];
                include_tags?: 0 | 1;
                include_votes?: 0 | 1;
                include_pools?: 0 | 1;
                filter?: 0 | 1;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["postV2"];
                };
            };
        };
    };
    list_tags: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                limit?: number;
                order?: "date" | "count" | "name";
                id?: number;
                after_id?: number;
                name?: string;
                name_pattern?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["tags"];
                };
            };
        };
    };
    list_related_tags: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                page?: components["parameters"]["Page"];
                order?: "date" | "count" | "name";
                id?: number;
                after_id?: number;
                name?: string;
                name_pattern?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["tagRelated"];
                };
            };
        };
    };
    list_artist: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                name?: string;
                order?: "date" | "name";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["artists"];
                };
            };
        };
    };
    list_users: {
        parameters: {
            query?: {
                id?: number;
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["users"];
                };
            };
        };
    };
    list_pools: {
        parameters: {
            query?: {
                query?: string;
                page?: components["parameters"]["Page"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["pools"];
                };
            };
        };
    };
    list_pool_posts: {
        parameters: {
            query: {
                id: number;
                page?: components["parameters"]["Page"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["poolPosts"];
                };
            };
        };
    };
}
